# Generated by Django 3.2.16 on 2022-12-01 10:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('table_ID', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('capacity', models.CharField(choices=[('1 Person', '1 Person'), ('2 People', '2 People'), ('3 People', '3 People'), ('4 People', '4 People'), ('5 People', '5 People'), ('6 People', '6 People'), ('7 People', '7 People'), ('8 People', '8 People'), ('9 People', '9 People'), ('10 People', '10 People')], max_length=10, unique=True)),
            ],
            options={
                'ordering': ['table_ID'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_testimony', to='yabash_app.author')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(default=datetime.datetime.now)),
                ('event_time', models.CharField(choices=[('08:00 am', '08:00 am'), ('09:00 am', '09:00 am'), ('10:00 am', '10:00 am'), ('11:00 am', '11:00 am'), ('12:00 pm', '12:00 pm'), ('13:00 pm', '13:00 pm'), ('14:00 pm', '14:00 pm'), ('15:00 pm', '15:00 pm'), ('16:00 pm', '16:00 pm'), ('17:00 pm', '17:00 pm'), ('18:00 pm', '18:00 pm'), ('19:00 pm', '19:00 pm'), ('20:00 pm', '20:00 pm'), ('21:00 pm', '21:00 pm'), ('22:00 pm', '22:00 pm')], default='08:00 am', max_length=10)),
                ('event_type', models.CharField(choices=[('Birthday Party', 'Birthday Party'), ('Meeting', 'Meeting'), ('Ceremony', 'Ceremony'), ('Private Reservation', 'Private Reservation')], default='Birthday Party', max_length=20)),
                ('event_info', models.CharField(blank=True, max_length=300, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reservation', to=settings.AUTH_USER_MODEL)),
                ('number_of_guest', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='table_capacity', to='yabash_app.table')),
            ],
            options={
                'ordering': ['created_on'],
                'unique_together': {('number_of_guest', 'event_date', 'event_time')},
            },
        ),
    ]
