# Generated by Django 3.2.16 on 2022-11-20 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yabash_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='capacity',
            field=models.IntegerField(choices=[('1 person', 1), ('2 person', 2), ('3 person', 3), ('4 person', 4), ('5 person', 5), ('6 person', 6), ('7 person', 7), ('8 person', 8), ('9 person', 9), ('10 person', 10)]),
        ),
    ]
