# Generated by Django 3.2.16 on 2022-11-17 00:12

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yabash_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline_text', models.CharField(max_length=200, unique=True)),
                ('sub_text', models.CharField(max_length=200, unique=True)),
                ('contact', models.CharField(max_length=50)),
                ('reservation', models.CharField(max_length=50)),
                ('images', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('opening_time', models.CharField(max_length=50)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='client',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
