# Generated by Django 3.2.16 on 2022-11-20 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yabash_app', '0002_alter_table_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='capacity',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eight'), (9, 'Nine'), (10, 'Ten')]),
        ),
    ]
