# Generated by Django 3.2.16 on 2022-11-19 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yabash_app', '0002_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eight'), (9, 'Nine'), (10, 'Ten')])),
                ('available', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('availability', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='no_of_guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_capacity', to='yabash_app.table'),
        ),
    ]
