# Generated by Django 3.2.16 on 2022-11-20 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yabash_app', '0003_alter_table_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='table_status',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
        migrations.AlterField(
            model_name='table',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
