# Generated by Django 3.2.16 on 2022-11-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yabash_app', '0003_alter_booking_event_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('number_of_guest', 'event_date', 'event_time')},
        ),
    ]
