# Generated by Django 3.2.16 on 2022-11-19 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yabash_app', '0005_auto_20221119_2023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['created_on']},
        ),
    ]
