# Generated by Django 3.2.16 on 2022-11-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yabash_app', '0005_alter_table_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='event_time',
            field=models.CharField(choices=[('08:00 am', '08:00 am'), ('10:00 am', '10:00 am'), ('12:00 pm', '12:00 pm'), ('14:00 pm', '14:00 pm'), ('16:00 pm', '16:00 pm'), ('18:00 pm', '18:00 pm'), ('20:00 pm', '20:00 pm'), ('22:00 pm', '22:00 pm')], default='12:00 pm', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.CharField(choices=[('BP', 'Birthday Party'), ('M', 'Meeting'), ('C', 'Ceremony'), ('PR', 'Private Reservation')], default='Birthday Party', max_length=20),
        ),
        migrations.AlterField(
            model_name='table',
            name='capacity',
            field=models.CharField(choices=[('1 Person', '1 Person'), ('2 People', '2 People'), ('3 People', '3 People'), ('4 People', '4 People'), ('5 People', '5 People'), ('6 People', '6 People'), ('7 People', '7 People'), ('8 People', '8 People'), ('9 People', '9 People'), ('10 People', '10 People')], default='2 People', max_length=10),
        ),
    ]
