# Generated by Django 3.2.16 on 2022-11-20 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yabash_app', '0006_auto_20221120_0948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='availability',
            new_name='updated_on',
        ),
        migrations.RemoveField(
            model_name='table',
            name='table_status',
        ),
    ]
