# Generated by Django 3.2.16 on 2022-11-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yabash_app', '0007_auto_20221120_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='capacity',
            field=models.CharField(choices=[(1, '1 Person'), (2, '2 People'), (3, '3 People'), (4, '4 People'), (5, '5 People'), (6, '6 People'), (7, '7 People'), (8, '8 People'), (9, '9 People'), (10, '10 People')], default='2 People', max_length=10),
        ),
    ]
