# Generated by Django 3.2.16 on 2022-11-20 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yabash_app', '0009_alter_table_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='event_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='booking',
            name='event_time',
            field=models.CharField(choices=[('08:00 am', '08:00 am'), ('10:00 am', '10:00 am'), ('12:00 pm', '12:00 pm'), ('14:00 pm', '14:00 pm'), ('16:00 pm', '16:00 pm'), ('18:00 pm', '18:00 pm'), ('20:00 pm', '20:00 pm'), ('22:00 pm', '22:00 pm')], default='10:00 am', max_length=10),
        ),
    ]
