# Generated by Django 3.2.16 on 2022-11-20 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yabash_app', '0010_auto_20221120_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='no_of_guest',
            new_name='number_of_guest',
        ),
    ]
