# Generated by Django 3.2.16 on 2022-11-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yabash_app', '0012_alter_booking_number_of_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='event_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='capacity',
            field=models.CharField(choices=[('1 Person', '1 Person'), ('2 People', '2 People'), ('3 People', '3 People'), ('4 People', '4 People'), ('5 People', '5 People'), ('6 People', '6 People'), ('7 People', '7 People'), ('8 People', '8 People'), ('9 People', '9 People'), ('10 People', '10 People')], max_length=10),
        ),
    ]
