# Generated by Django 3.2.16 on 2022-11-20 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yabash_app', '0013_auto_20221120_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='number_of_guest',
            field=models.ForeignKey(default='5 People', on_delete=django.db.models.deletion.CASCADE, related_name='table_capacity', to='yabash_app.table'),
        ),
    ]
